config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'vacations#index'
  #resources :vacations
  #resources :legs, only: [:show, :index] do
  #  resources :itinerary_items, only: [:show, :index]
  #end

  resources :vacations

  resources :legs do
    resources :itinerary_items, only: [:show, :index, :new, :create, :edit]
  end

  resources :itinerary_items

  get 'destinations/:destination_id/attractions/under20', to: 'attractions#under20', :as => :under20
  get 'destinations/mine', to: 'destinations#my_destinations', :as => :user_destinations

  resources :destinations do
    resources :attractions, only: [:show, :index, :new, :create, :edit]
  end

  resources :attractions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#logout'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resources :users

  authenticated :user do 
    root 'vacations#index', as: :authenticated_root
  end

  root 'destinations#index'
end

app/models/vacation.rb
class Vacation < ApplicationRecord
    belongs_to :user
    has_many :legs
    has_many :destinations, through: :legs
    validates_with DateValidator
    validates :name, presence: { message: "cannot be blank." }

    def self.permit_view(user, object)
        if object.present? && user.present?
            @vacation = Vacation.where("user_id = ? and id = ?", user.id, object.vacation.id)
        else
            nil
        end
    end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
    include Devise::Controllers::Helpers
    before_action :authenticate_user!, raise: false, except: [:edit]
    
    def index
        @vacations = current_user.vacations
    end

    def new
        @vacation = Vacation.new
    end

    def show
        @vacation = current_user.vacations.find_by(:id => params[:id])
       if @vacation.nil?
            flash[:alert] = "You don't have access to view that."
            redirect_to "/"
       else
            @sorted_legs = Leg.sort(@vacation.id)
       end

    end

    def edit
        @vacation = current_user.vacations.find_by(:id => params[:id])
        if @vacation.nil?
            flash[:alert] = "You don't have access to view that."
            redirect_to "/"
        end
    end

    def create
       @vacation = current_user.vacations.new(vacation_params)
       if @vacation.save
        flash[:notice] = "Vacation Created."
        redirect_to vacation_path(@vacation)
       else
        flash[:alert] = "Error in creating vacation."
        flash[:alert] += helpers.flash_error_message(@vacation)
        redirect_to new_vacation_path
       end
    end

    def update
        @vacation = current_user.vacations.find_by(:id => params[:id])
        if !@vacation.present?
            flash[:alert] = "You don't have permissions to do that."
            redirect_to "/"
        else
            if @vacation.update(vacation_params)
                flash[:notice] = "Edit vacation successful."
                redirect_to vacation_path(@vacation)
            else
                flash[:alert] = "Editing vacation failed."
                flash[:alert] += helpers.flash_error_message(@vacation)
                redirect_to vacation_path(@vacation)
            end
        end
    end

    def destroy
        @vacation = current_user.vacations.find_by(:id => params[:id])
        if @vacation.present? && @vacation.destroy
            flash[:notice] = "Vacation Deleted."
            redirect_to vacations_path
        else
            flash[:alert] = "You don't have permissions to do that."
            redirect_to "/"
        end
    end

    private
    def vacation_params
        params.require(:vacation).permit(:name, :start_date, :end_date)
    end
end

app/views/vacations/edit.html.erb
<!-- vacations/edit.html.erb -->

<h2>Edit a Vacation</h2>

<%= form_for(@vacation) do |f| %>
    <%= f.label :name, "Name:" %><br/>
    <%= f.text_field :name %><br/>
    <%= f.label :start_date, "Start Date" %><br/>
    <%= f.datetime_select :start_date %><br/>

    <%= f.label :end_date, "End Date"%><br/>
    <%= f.datetime_select :end_date %><br/>

    <%= f.submit "Edit Vacation Details"%>
<% end %>

<div class="mini-nav">
    <%= link_to "Cancel", vacations_path %>
</div>

app/views/vacations/index.html.erb
<!-- all vacations are spelled out here -->
<!-- Location: vacations/index.html.erb -->

<p><b>Hello, <%= current_user.first_name %></b></p>

<p>
<% @vacations.each do |vacation| %>
    <h2><%= link_to vacation.name, vacation_path(vacation) %></h2>
    <p>
    <% if vacation.start_date.present? %>
      <%= vacation.start_date %> - <%= vacation.end_date %><br/>
    <% end %>
    </p>
<% end %>
</p>

app/views/vacations/new.html.erb
<!-- create a new vacation -->
<!-- vacations/new.html.erb -->

<h2>Create A New Vacation</h2>

<%= form_for @vacation do |f| %>
    <%= f.label :name, "Trip Name" %><br/>
    <%= f.text_field :name %><br/>

    <%= f.label :start_date, "First Day Of Trip" %><br/>
    <%= f.datetime_select :start_date %><br />
    
    <%= f.label :end_date, "Last Day of Trip" %><br/>
    <%= f.datetime_select :end_date %><br />

    <%= f.submit "Submit" %>
<% end %>

<div class="mini-nav">
<%= link_to "Cancel", vacations_path %>
</div>

app/views/vacations/show.html.erb
<!--vacations/show.html.erb -->

<h2><%= @vacation.name %></h2>
<p>
<% if @vacation.start_date? %>
    <%= @vacation.start_date %>
    <%= @vacation.end_date %>
    <% @sorted_legs.each do |leg| %>
        <h2><%= link_to "#{Destination.find_by(:id=>leg.departure_id).city_name} -
            #{Destination.find_by(:id => leg.destination_id).city_name}", leg_path(leg) %></h2>
    <% end %>
<% end %>
</p>

<%= link_to "Delete Vacation", vacation_path(@vacation), method: :delete %>
<%= link_to "Edit Vacation", edit_vacation_path(@vacation) %>
<%= link_to "Add a Leg", new_leg_path %>