config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'vacations#index'
  #resources :vacations
  #resources :legs, only: [:show, :index] do
  #  resources :itinerary_items, only: [:show, :index]
  #end

  resources :vacations

  resources :legs do
    resources :itinerary_items, only: [:show, :index, :new, :create, :edit]
  end

  resources :itinerary_items

  get 'destinations/:destination_id/attractions/under20', to: 'attractions#under20', :as => :under20
  get 'destinations/mine', to: 'destinations#my_destinations', :as => :user_destinations

  resources :destinations do
    resources :attractions, only: [:show, :index, :new, :create, :edit]
  end

  resources :attractions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#logout'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resources :users

  authenticated :user do 
    root 'vacations#index', as: :authenticated_root
  end

  root 'destinations#index'
end

app/models/leg.rb
class Leg < ApplicationRecord
    belongs_to :vacation
    belongs_to :destination
    has_many :itinerary_items
    validates :departure_id, presence: true
    validates :destination_id, presence: true
    validates :leg_num, uniqueness: { scope: :vacation, message: "has been set already"}
    validate :departure_destination_cannot_be_same

    def self.sort(vacation_id)
        Leg.where(:vacation_id => vacation_id).order(:leg_num)
    end

    def departure_destination_cannot_be_same
        if departure_id == destination_id
            errors.add(:destination_id, "cannot be the same as departure location")
        end
    end

end

app/controllers/legs_controller.rb
class LegsController < ApplicationController
    before_action :authenticate_user!, raise: false, except: [:update]

    def index
       #if (params[:vacation_id])
       #   @legs = current_user.vacations.find_by(:id => params[:vacation_id]).legs
       #   @legs = Vacation.find_by(:id => params[:vacation_id]).legs
       #else
           redirect_to '/'
       #end
    end

    def new
        @leg = Leg.new(:id => params[:id])
        @destinations = Destination.all
    end

    def show
        @leg = Leg.find_by(:id => params[:id])
        if !(Vacation.permit_view(current_user, @leg)).present?
            flash[:alert] = "You don't have permission to do that."
            redirect_to '/'
        else
            @itinerary_items = ItineraryItem.sort(@leg.id)
            @destination_city_name = Destination.find_by(:id => @leg.destination_id).city_name
            @departure_city_name = Destination.find_by(:id => @leg.departure_id).city_name
        end
    end

    def edit
        @leg = Leg.find_by(:id => params[:id])
        if !@leg.present? || Vacation.permit_view(current_user, @leg).empty?
            flash[:alert] = "You don't have permission to do that."
            redirect_to '/'
        else
            @destinations = Destination.all
        end
    end

    def create
        @leg = Leg.new(leg_params)
        if @leg.save
            flash[:notice] = "Added Leg to #{@leg.vacation.name}"
            redirect_to leg_path(@leg)
        else
            flash[:notice] = "Failed creating new leg."
            flash[:alert] = helpers.flash_error_message(@leg)
            @destinations = Destination.all
            redirect_to '/'
        end
    end

    def update
        @leg = Leg.find_by(:id => params[:id])
        if !@leg.present? || !Vacation.permit_view(current_user, @leg).present?
            flash[:alert] = "You don't have permission to do that."
            redirect_to '/'
        else
            if @leg.update(leg_params)
                flash[:notice] = "Updated leg information."
                redirect_to leg_path(@leg)
            else
                flash[:notice] = "Failed updating leg."
                flash[:alert] = helpers.flash_error_message(@leg)
                redirect_to '/'
            end
        end
    end

    def destroy
        @leg = Leg.find_by(:id => params[:id])
        if !@leg.present? || Vacation.permit_view(current_user, @leg).empty?
            flash[:notice] = "You don't have permission to do that."
            redirect_to '/'
        else
            @vacation = @leg.vacation
            @leg.destroy
            flash[:notice] = "Leg Deleted."
            redirect_to vacation_path(@vacation)
        end
    end

    private
    def leg_params
        params.require(:leg).permit(:departure_id, :destination_id, :leg_num, :vacation_id)
    end
end

app/views/legs/edit.html.erb
<!--legs/edit-->

<h2>Edit Leg</h2>

<%= form_for @leg do |f| %>
    <%= f.label :departure_id, "Departure City: "%><br/>
    <%= f.collection_select :departure_id, @destinations, :id, :city_name, {:selected => @leg.departure_id} %><br/>
    <%= f.label :destination_id, "Destination:" %><br/>
    <%= f.collection_select :destination_id, @destinations, :id, :city_name, {:selected => @leg.destination_id} %><br/>
    <%= f.label :leg_num, "Which Leg:" %><br/>
    <%= f.number_field :leg_num, min: 1, :value => @leg.leg_num %><br/>
    <%= f.label :vacation_id, "Vacation:" %><br/>
    <%= f.collection_select :vacation_id, current_user.vacations, :id, :name, {:selected => @leg.vacation_id} %><br/>
    <%= f.submit "Submit Leg" %>
<% end %>

<div class="mini-nav">
    <%= link_to "Cancel", leg_path(@leg) %>
</div>

app/views/legs/index.html.erb
<!--legs/index -->

<% @legs.each do |leg| %>
    <%= leg.arrival_city_name %>
    <%= link_to leg.vacation.name, vacation_legs_path(leg.vacation)%>
<% end %>

app/views/legs/new.html.erb
<!-- legs/new.html -->

<h2>Add a Leg</h2>

<%= form_for @leg do |f| %>
    <%= f.label :departure_id, "Departure City:" %> 
    <%= f.collection_select :departure_id, @destinations, :id, :city_name %><br/>

    <%= f.label :destination_id, "Destination:" %> 
    <%= f.collection_select :destination_id, @destinations, :id, :city_name %><br/>

    <%= f.label :leg_num, "Which Leg:" %> 
    <%= f.number_field :leg_num, min: 1, value: 1 %><br/>

    <%= f.label :vacation_id, "Vacation:" %> 
    <%= f.collection_select :vacation_id, current_user.vacations, :id, :name%><br/>
    <%= f.submit "Submit Leg" %>
<% end %>

<div class="mini-nav">
    <%= link_to "Cancel", vacations_path %>
</div>

app/views/legs/show.html.erb
<!--legs/show-->

<h1>
<%= @departure_city_name %> - <%= @destination_city_name %> Leg</h1>
<div>
Back to <%= link_to @leg.vacation.name, vacation_path(@leg.vacation) %> | 
<%= link_to "Edit Leg", edit_leg_path(@leg) %> | 
<%= link_to "Add Leg", new_leg_path %> | 
<%= link_to "Delete Leg", leg_path(@leg), method: :delete, data: { confirm: "Are you sure you want to delete?"} %>
</div>


<h3>Itinerary</h3>

<% @itinerary_items.each do |item| %>
    <p>
    <b>Day <%= item.day_of_trip %></b><br/>
    Activity Time: <%= item.time %><br/>
    Type of Activity: <%= item.type_of_activity %><br/>
    <% if item.type_of_activity == "Event" %>
        Attraction: <%= ApplicationHelper.attraction(item).name %><br/>
    <% end %>
    <%= link_to "Edit Item", edit_leg_itinerary_item_path(@leg, item) %>
    <%= link_to "Delete Item", itinerary_item_path(item), method: :delete, data: { confirm: "Are you sure you want to delete?"} %><br/>
    </p>
<% end %>
<p>
<%= link_to "Add Itinerary Item", new_leg_itinerary_item_path(@leg) %><br/>
</p>