config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'vacations#index'
  #resources :vacations
  #resources :legs, only: [:show, :index] do
  #  resources :itinerary_items, only: [:show, :index]
  #end

  resources :vacations

  resources :legs do
    resources :itinerary_items, only: [:show, :index, :new, :create, :edit]
  end

  resources :itinerary_items

  get 'destinations/:destination_id/attractions/under20', to: 'attractions#under20', :as => :under20
  get 'destinations/mine', to: 'destinations#my_destinations', :as => :user_destinations

  resources :destinations do
    resources :attractions, only: [:show, :index, :new, :create, :edit]
  end

  resources :attractions

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#logout'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  resources :users

  authenticated :user do 
    root 'vacations#index', as: :authenticated_root
  end

  root 'destinations#index'
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :legs
    has_many :vacations, through: :legs
    has_many :attractions
    validates :city_name, presence: { message: 'cannot be blank.' }
    validates :country_name, presence: { message: 'cannot be blank.' }
    validates_uniqueness_of :city_name, scope: [:state_name, :country_name], message: 'already entered.'
    validates_format_of :city_name, :country_name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/

    def self.user_destinations(user)

        user_destinations = []
        user.vacations.each do |vacation|
            vacation.destinations.uniq.each do |dest|
                if !user_destinations.include?(dest)
                    user_destinations << Destination.find_by(:id => dest.id)
                end
            end
        end
        return user_destinations
    end

    def self.find_destination(city)
        Destination.where(city_name: city)
    end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :authenticate_user!, raise: false, except: [:index, :show]

    def index
        if params[:city_name].present?
            @destinations = Destination.find_destination(params[:city_name])
        else
            @destinations = Destination.all
        end
    end

    def new
        @destination = Destination.new
    end

    def show
        @destination = Destination.find_by(:id => params[:id])
    end

    def create
        @destination = Destination.new(destination_params)
        if @destination.save
            flash[:notice] = "Destination created."
            redirect_to destination_path(@destination)
        else
            flash[:notice] = "Destination Failed."
            flash[:alert] = helpers.flash_error_message(@destination)
            redirect_to destinations_path
        end
    end

    def edit
        @destination = Destination.find_by(:id => params[:id])
    end

    def update
        @destination = Destination.find_by(:id => params[:id])
        if @destination.update(destination_params)
            redirect_to destination_path(@destination)
        else
            flash[:notice] = "Edit Destination Failed."
            redirect_to destinations_path
        end
    end

    def destroy
        @destination = Destination.find_by(:id => params[:id])
        @destination.destroy
        redirect_to destinations_path
    end

    def my_destinations
        @destinations = Destination.user_destinations(current_user)
    end

    private
    def destination_params
        params.require(:destination).permit(:city_name, :country_name)
    end

end

app/views/destinations/edit.html.erb
<!-- destinations/edit -->

<h2>Edit Destination</h2>

<div class="content">
<%= form_for @destination do |f| %>
    <%= f.label :city_name, "City Name" %><br/>
    <%= f.text_field :city_name %><br/>
    <%= f.label :country_name, "Country Name" %><br/>
    <%= f.text_field :country_name %><br/>
    <%= f.submit "Edit Place" %>
<% end %>
</div>

<div class="mini-nav">
    <%= link_to "Cancel", destination_path(@destination) %>
</div>

app/views/destinations/index.html.erb
<!--destinations/index-->

<h1>Start Planning Your Trip!</h1>

<p>The Possibilities are Endless...</p>

<%= form_tag(destinations_path, method: "get") do %>
    <%= label_tag(:city_name, "Search for City:") %>
    <%= text_field_tag(:city_name) %>
    <%= submit_tag("Search") %>
<% end %>

<% @destinations.each do |destination| %>
    <p><%= link_to "#{destination.city_name}, #{destination.state_name} #{destination.country_name}", destination_path(destination) %></p>
<% end %>

<% if user_signed_in? %>
<%= link_to("Add New Destination", new_destination_path) %><br/>
<% end %>

app/views/destinations/my_destinations.html.erb
<% @destinations.each do |destination| %>
    <p>
    <h2><%= destination.city_name %></h2>
    <% destination.vacations.each do |vacation|%>
        <% if vacation.user == current_user %>
            <span class="vacation"><%= link_to vacation.name, vacation_path(vacation) %></span>
        <% end %>
    <% end %>
    </p>
<% end %>

app/views/destinations/new.html.erb
<!--destination/new -->

<h1>Add a New Destination</h1>

<%= form_for @destination do |f|%>
    <%= f.label :city_name, "City" %><br/>
    <%= f.text_field :city_name %><br/>
    <!--
    <%= f.text_field :state_name %>
    <%= f.text_field :state_code %>
    -->
    <%= f.label :country_name, "Country" %><br/>
    <%= f.text_field :country_name %><br/>
    <!--
    <%= f.text_field :country_code %>
    -->
    <%= f.submit "Submit Form" %>
<% end %>

app/views/destinations/show.html.erb
<!--destinations/show-->

<h1><%= @destination.city_name %></h1>
<%= link_to "Edit Destination", edit_destination_path(@destination) %>
<%= link_to "Delete Destination", destination_path(@destination), method: :delete %>

<div class="content">
<% @destination.attractions.each do |a| %>
    <p>
    <%= link_to a.name, destination_attraction_path(@destination, a) %><br/>
    <%= a.admission == 0 ? "Free" : "$#{a.admission}" %>
    </p>
<% end %>
</div>

<div class="mini-nav">
<%= link_to "< Back to All Destinations", destinations_path, :class => "mini-nav" %> |
<%= link_to "Attractions < $20", under20_path(@destination), :class => "mini-nav" %> | 
<%= link_to "Add a new Attraction", new_destination_attraction_path(@destination), :class => "mini-nav" %>
</div>